export default {
  REWARD_CREATE: 'REWARD_CREATE',
  REWARD_CREATE_START: 'REWARD_CREATE_START',
  REWARD_CREATE_SUCCESS: 'REWARD_CREATE_SUCCESS',
  REWARD_CREATE_FAILUE: 'REWARD_CREATE_FAILUE',

  GET_REWARD: 'GET_REWARD',
  GET_REWARD_START: 'GET_REWARD_START',
  GET_REWARD_SUCCESS: 'GET_REWARD_SUCCESS',
  GET_REWARD_FAILURE: 'GET_REWARD_FAILURE',

  GET_CURRENT_REWARD: 'GET_CURRENT_REWARD',
  GET_CURRENT_REWARD_START: 'GET_CURRENT_REWARD_START',
  GET_CURRENT_REWARD_SUCCESS: 'GET_CURRENT_REWARD_SUCCESS',
  GET_CURRENT_REWARD_FAILURE: 'GET_CURRENT_REWARD_FAILURE',
};
