export default {
  ADD_CRIME: 'ADD_CRIME',
  ADD_CRIME_SUCCESS: 'ADD_CRIME_SUCCESS',
  ADD_CRIME_FAILURE: 'ADD_CRIME_FAILURE',
  ADD_CRIME_START: 'ADD_CRIME_START',

  GET_CRIMES: 'GET_CRIMES',
  GET_CRIMES_SUCCESS: 'GET_CRIMES_SUCCESS',
  GET_CRIMES_FAILURE: 'GET_CRIMES_FAILURE',
  GET_CRIMES_START: 'GET_CRIMES_START',

  ALERT_CRIME: 'ALERT_CRIME',
  ALERT_DANGER: 'ALERT_DANGER',
  ADD_NEW_INCIDENT: 'ADD_NEW_INCIDENT',
  SHOW_ADD_MODAL: 'SHOW_ADD_MODAL',
  CLOSE_ADD_MODAL: 'CLOSE_ADD_MODAL',
};
