export default {
  LOGIN: 'LOGIN',
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILUE: 'LOGIN_FAILUE',

  REGISTER: 'REGISTER',
  REGISTER_START: 'REGISTER_START',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILUE: 'REGISTER_FAILUE',

  LOGOUT: 'LOGOUT',
  LOGOUT_START: 'LOGOUT_START',
};
